// <auto-generated />
using System;
using Core_Project.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core_Project.Repository.Migrations
{
    [DbContext(typeof(Core_ProjectContext))]
    [Migration("20191006182241_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Core_Project.Domain.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataCadastro");

                    b.Property<int>("Documento");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Core_Project.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Nome");

                    b.Property<int>("ProdutoDetalhesId");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Core_Project.Domain.ProdutoDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Peso");

                    b.Property<int?>("ProdutoId");

                    b.Property<int>("Quantidade");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("ProdutoDetalhes");
                });

            modelBuilder.Entity("Core_Project.Domain.Produto", b =>
                {
                    b.HasOne("Core_Project.Domain.Cliente")
                        .WithMany("Produtos")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("Core_Project.Domain.ProdutoDetalhe", b =>
                {
                    b.HasOne("Core_Project.Domain.Produto")
                        .WithOne("ProdutoDetalhe")
                        .HasForeignKey("Core_Project.Domain.ProdutoDetalhe", "ProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
